'use client';
import { useEffect,useState } from 'react'; import Input from '@/components/ui/Input'; import Button from '@/components/ui/Button'; import { KeyRound,Eye } from 'lucide-react';
type Item={id:string;service_name:string;account_login:string;notes:string|null};
export default function VaultPage(){const[items,setItems]=useState<Item[]>([]),[service,setService]=useState(''),[login,setLogin]=useState(''),[secret,setSecret]=useState(''),[notes,setNotes]=useState(''),[error,setError]=useState(''),[shown,setShown]=useState<Record<string,string>>({});
 const[shareWith,setShareWith]=useState<Record<string,string>>({}),[notice,setNotice]=useState('');
 const load=()=>fetch('/api/vault').then(r=>r.json()).then(d=>setItems(d.items||[]));useEffect(()=>{void load();},[]);
 async function save(e:React.FormEvent){e.preventDefault();setError('');const r=await fetch('/api/vault',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({service_name:service,account_login:login,secret,notes})});const d=await r.json();if(!r.ok)setError(d.error);else{setService('');setLogin('');setSecret('');setNotes('');load();}}
 async function reveal(id:string){const r=await fetch('/api/vault',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'reveal',id})});const d=await r.json();if(!r.ok)setError(d.error);else{setShown(s=>({...s,[id]:d.secret}));setTimeout(()=>setShown(s=>({...s,[id]:''})),30000);}}
 async function share(id:string){setError('');setNotice('');const r=await fetch('/api/vault',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'share',id,share_with:shareWith[id]})});const d=await r.json();if(!r.ok)setError(d.error);else{setNotice(`Acesso compartilhado com ${d.recipient}.`);setShareWith(s=>({...s,[id]:''}));}}
 return <div className="mx-auto max-w-4xl space-y-6 p-4 sm:p-6"><header className="rounded-3xl bg-gradient-to-br from-violet-700 to-slate-900 p-6 text-white"><h1 className="flex items-center gap-3 text-2xl font-bold"><KeyRound/>Cofre familiar</h1><p className="mt-2 text-white/80">Credenciais protegidas. A senha aparece por 30 segundos e nunca vai para o WhatsApp.</p></header>
 <form onSubmit={save} className="grid gap-3 rounded-2xl border bg-white p-5 sm:grid-cols-2"><h2 className="sm:col-span-2 font-bold">Adicionar acesso</h2><Input label="Serviço" value={service} onChange={e=>setService(e.target.value)} placeholder="Netflix, Spotify..." required/><Input label="Login ou e-mail" value={login} onChange={e=>setLogin(e.target.value)} required/><Input label="Senha" type="password" value={secret} onChange={e=>setSecret(e.target.value)} required/><Input label="Observação" value={notes} onChange={e=>setNotes(e.target.value)}/>{error&&<p className="sm:col-span-2 text-sm text-red-700">{error}</p>}<Button type="submit" className="sm:col-span-2 sm:w-fit">Guardar com segurança</Button></form>
 {notice&&<p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p>}<section className="grid gap-3 sm:grid-cols-2">{items.map(item=><article key={item.id} className="rounded-xl border bg-white p-4"><h3 className="font-bold text-slate-900">{item.service_name}</h3><p className="text-sm text-slate-600">{item.account_login}</p><p className="mt-2 rounded bg-slate-100 p-2 font-mono text-sm text-slate-900">{shown[item.id]||'••••••••••••'}</p><Button type="button" variant="outline" size="sm" className="mt-3" onClick={()=>reveal(item.id)}><Eye className="h-4 w-4"/>Ver por 30 segundos</Button><div className="mt-4 border-t pt-3"><p className="mb-2 text-xs font-semibold text-slate-700">Compartilhar com pessoa cadastrada</p><div className="flex gap-2"><input aria-label="E-mail ou CPF" value={shareWith[item.id]||''} onChange={e=>setShareWith(s=>({...s,[item.id]:e.target.value}))} placeholder="E-mail ou CPF" className="min-w-0 flex-1 rounded-lg border px-3 py-2 text-sm"/><Button type="button" size="sm" onClick={()=>share(item.id)} disabled={!shareWith[item.id]?.trim()}>Liberar</Button></div></div></article>)}</section></div>}
