import Link from 'next/link';
import { ShieldCheck } from 'lucide-react';

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="space-y-2"><h2 className="text-xl font-bold text-slate-950">{title}</h2><div className="space-y-3 text-sm leading-7 text-slate-700">{children}</div></section>;

export default function PrivacyPage() {
  return <main className="min-h-screen bg-slate-50 px-4 py-8 sm:py-12"><article className="mx-auto max-w-3xl space-y-8 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-10">
    <header className="space-y-3 border-b border-slate-200 pb-7"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-100 text-emerald-700"><ShieldCheck /></div><h1 className="text-3xl font-bold text-slate-950">Política de Privacidade da Iasmin</h1><p className="text-sm text-slate-500">Última atualização: 19 de setembro de 2026</p><p className="leading-7 text-slate-700">Esta política explica como a Iasmin utiliza e protege seus dados pessoais.</p></header>
    <Section title="1. Responsável pelos dados"><p>A Iasmin é operada por <strong>Gedaias Moura</strong>, pessoa natural localizada em Caraguatatuba/SP e responsável pelas decisões sobre o tratamento de dados.</p><p>Contato de privacidade: <a className="font-semibold text-emerald-700 underline" href="mailto:gedaias.moura@hotmail.com">gedaias.moura@hotmail.com</a> · Instagram: <a className="font-semibold text-emerald-700 underline" href="https://instagram.com/gedmoura">@gedmoura</a>.</p></Section>
    <Section title="2. Dados tratados"><p>Podemos tratar nome, apelido, CPF, nascimento, e-mail, WhatsApp, foto, endereço, contato de emergência ou apoio, dados de acesso, módulos liberados, tarefas, lembretes, mensagens e informações inseridas nos recursos da plataforma.</p><p>Jornadas, dependência, recuperação e pedidos de apoio podem revelar dados pessoais sensíveis e recebem proteção reforçada.</p></Section>
    <Section title="3. Finalidades e bases legais"><p>Usamos os dados para criar e proteger a conta, prestar os serviços solicitados, administrar jornadas e comunidades, enviar mensagens e lembretes, atender solicitações e cumprir obrigações legais. Conforme a finalidade, o tratamento pode se basear em contrato, obrigação legal, exercício de direitos, legítimo interesse, proteção da vida e consentimento.</p></Section>
    <Section title="4. Comunidades e apoio"><p>O apelido e a foto escolhidos podem aparecer nas comunidades. Ao entrar em um grupo, a pessoa participa do ranking daquele grupo. Registros diários e anotações continuam privados, salvo compartilhamento escolhido pela própria pessoa.</p><p>Pedidos de apoio somente serão enviados a contato de confiança, comunidade ou administrador após escolha e confirmação, salvo obrigação legal.</p></Section>
    <Section title="5. Fornecedores e inteligência artificial"><p>Podemos utilizar fornecedores de hospedagem, banco de dados, autenticação, e-mail, WhatsApp e inteligência artificial, incluindo Supabase, Vercel, Evolution API/WhatsApp e o provedor de IA configurado. Eles recebem apenas os dados necessários à função contratada. Não vendemos dados pessoais.</p><p>Mensagens dirigidas à Iasmin podem ser processadas por inteligência artificial. Lembretes automáticos com texto pronto podem ser enviados sem nova análise por IA.</p></Section>
    <Section title="6. Segurança e retenção"><p>Adotamos controle de acesso, autenticação, registros de segurança e criptografia para credenciais do cofre. Os dados ficam armazenados pelo tempo necessário para prestar o serviço, cumprir obrigações, prevenir fraude e exercer direitos, sendo depois eliminados ou anonimizados quando cabível.</p></Section>
    <Section title="7. Seus direitos"><p>Você pode solicitar confirmação, acesso, correção, informação sobre compartilhamentos, oposição, portabilidade, anonimização, bloqueio, eliminação e revogação do consentimento, quando aplicável. Envie o pedido para <a className="font-semibold text-emerald-700 underline" href="mailto:gedaias.moura@hotmail.com">gedaias.moura@hotmail.com</a>. Podemos confirmar sua identidade antes de atender ao pedido.</p></Section>
    <Section title="8. Uso responsável"><p>A versão atual é destinada a maiores de 18 anos. A Iasmin não substitui atendimento médico, psicológico ou serviços de emergência.</p></Section>
    <Section title="9. Alterações"><p>Esta política pode ser atualizada quando houver mudanças nos recursos, fornecedores ou na legislação. Mudanças relevantes serão informadas pelos canais disponíveis.</p></Section>
    <footer className="border-t border-slate-200 pt-6"><Link href="/login" className="font-semibold text-emerald-700 hover:underline">← Voltar para a Iasmin</Link></footer>
  </article></main>;
}
