'use client';
import {useEffect,useState} from 'react'; import Link from 'next/link'; 
import {AddictionTracker} from '@/types/addiction'; import {JourneyHomeCard} from '@/components/addiction/JourneyHomeCard'; import {CommunityFeed} from '@/components/addiction/CommunityFeed'; import {CreatePostModal} from '@/components/addiction/CreatePostModal'; import {DiscoverView} from '@/components/addiction/DiscoverView'; import {Compass,Flame,Plus,Users,X} from 'lucide-react';
type Group={id:string;name:string;description?:string;ranking_enabled:boolean;image_url?:string|null;membership?:{status:string};member_count?:number;best_days?:number};
export default function AddictionPage(){const[trackers,setTrackers]=useState<AddictionTracker[]>([]),[checkins,setCheckins]=useState<Record<string,string>>({}),[groups,setGroups]=useState<Group[]>([]),[tab,setTab]=useState<'today'|'community'|'discover'>('today'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[feedKey,setFeedKey]=useState(0),[created,setCreated]=useState<string|null>(null);
async function load(){const[t,c,g]=await Promise.all([fetch('/api/addiction/trackers').then(r=>r.json()),fetch('/api/addiction/checkins').then(r=>r.json()),fetch('/api/addiction/groups').then(r=>r.json())]);setTrackers(t.trackers||[]);setCheckins(Object.fromEntries((c.checkins||[]).map((x:{tracker_id:string;status:string})=>[x.tracker_id,x.status])));setGroups((g.groups||[]).filter((x:Group)=>x.membership?.status==='active'));setLoading(false)}useEffect(()=>{const p=new URLSearchParams(window.location.search);const requested=p.get('tab');if(requested==='community'||requested==='discover')setTab(requested);setCreated(p.get('created'));void load()},[]);
async function answer(id:string,status:string){setError('');const r=await fetch('/api/addiction/checkins',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tracker_id:id,status})});const d=await r.json();if(!r.ok){setError(d.error||'Não foi possível registrar');return}setCheckins(s=>({...s,[id]:status}));await load()}
const createdTracker=trackers.find(t=>t.id===created);
return <div className="mx-auto min-h-full max-w-3xl bg-white pb-28"><div className="space-y-5 p-4 sm:p-6">
{tab==='today'&&<><header className="flex items-center justify-between gap-3"><div><h1 className="text-3xl font-black text-slate-950">Bom dia 👋</h1><p className="text-sm text-slate-600">Acompanhe seu dia e seus grupos.</p></div><Link href="/addiction/novo" className="inline-flex min-h-11 items-center gap-2 rounded-xl border-2 border-blue-600 px-4 text-sm font-black text-blue-700"><Plus className="h-5 w-5"/>Nova jornada</Link></header>
{created&&createdTracker&&<section className="relative overflow-hidden rounded-3xl bg-gradient-to-r from-emerald-100 via-cyan-100 to-purple-100 p-5 shadow"><button onClick={()=>setCreated(null)} className="absolute right-3 top-3"><X className="h-5 w-5"/></button><div className="flex gap-4"><span className="text-5xl">✅</span><div><p className="font-black text-emerald-900">Nova jornada criada!</p><h2 className="text-2xl font-black text-slate-950">{createdTracker.name}</h2><p className="text-slate-700">{createdTracker.goal_days?`Você se desafiou por ${createdTracker.goal_days} dias.`:'Sua jornada continuará sem prazo.'}</p></div></div><div className="mt-4 rounded-2xl bg-white/70 p-3"><p className="mb-2 text-sm font-black text-slate-900">Seus acompanhamentos pelo WhatsApp</p><div className="flex flex-wrap gap-2">{[3,7,15,createdTracker.goal_days].filter((v,i,a):v is number=>!!v&&a.indexOf(v)===i).map(d=><span key={d} className="rounded-full bg-blue-600 px-3 py-1 text-xs font-bold text-white">{d} dias</span>)}</div><p className="mt-2 text-xs text-slate-600">Depois da meta, os dias continuam contando automaticamente.</p></div></section>}
{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}{loading?<p className="p-8 text-center">Carregando...</p>:trackers.length?trackers.map(t=><JourneyHomeCard key={t.id} tracker={t} checkin={checkins[t.id]} onCheckin={answer} onCommunity={()=>setTab('community')}/>):<Link href="/addiction/novo" className="block rounded-3xl border-2 border-dashed border-blue-300 bg-blue-50 p-10 text-center font-black text-blue-700">+ Começar minha primeira jornada</Link>}
<section className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-xl font-black text-slate-950">Seus grupos</h2><Link href="/addiction/grupos" className="font-bold text-blue-700">Ver todos ›</Link></div>{groups.length?<div className="space-y-3">{groups.slice(0,3).map((g,i)=><Link key={g.id} href={`/addiction/grupos/${g.id}`} className={`block overflow-hidden rounded-3xl border-2 shadow-sm ${i%2?'border-purple-200 bg-gradient-to-r from-purple-50 to-fuchsia-100':'border-cyan-200 bg-gradient-to-r from-cyan-50 to-emerald-100'}`}><div className="flex items-center gap-3 p-3">{g.image_url?<img src={g.image_url} alt="" className="h-20 w-24 rounded-2xl object-cover shadow"/>:<span className="flex h-20 w-24 items-center justify-center rounded-2xl bg-white/70 text-5xl shadow-sm">{i%2?'🎬':'🌱'}</span>}<div className="min-w-0 flex-1"><h3 className="font-black text-slate-950">{g.name}</h3><div className="mt-2 flex flex-wrap gap-2"><span className="rounded-full bg-white/80 px-2 py-1 text-xs font-bold text-slate-700">👥 {g.member_count||1} {(g.member_count||1)===1?'participante':'participantes'}</span>{g.ranking_enabled&&<span className="rounded-full bg-white/80 px-2 py-1 text-xs font-bold text-blue-800">🏆 Melhor: {g.best_days||0} dias</span>}</div><p className="mt-2 text-xs font-bold text-blue-700">Abrir participantes{g.ranking_enabled?' e ranking':''} ›</p></div></div></Link>)}</div>:<p className="rounded-2xl bg-purple-50 p-4 text-sm text-purple-900">Você ainda não participa de uma comunidade.</p>}<Link href="/addiction/grupos" className="block rounded-3xl border-2 border-dashed border-blue-300 bg-gradient-to-r from-blue-50 to-purple-50 p-5 text-center font-black text-blue-700">🔭 Descobrir novas comunidades</Link></section></>}
{tab==='community'&&<><header><h1 className="text-3xl font-black text-slate-950">Comunidade</h1><p className="text-slate-600">Compartilhe, inspire e caminhe junto.</p></header><section className="rounded-3xl bg-gradient-to-br from-emerald-100 via-cyan-100 to-purple-100 p-5"><div className="flex items-center justify-between gap-3"><p className="font-bold text-slate-700">O que você quer compartilhar hoje?</p>{trackers[0]&&<CreatePostModal trackerId={trackers[0].id} onSuccess={()=>setFeedKey(k=>k+1)}/>}</div></section><CommunityFeed type="all" limit={30} userTrackerId={trackers[0]?.id} refreshKey={feedKey}/></>}
{tab==='discover'&&<DiscoverView/>}
</div><nav className="fixed inset-x-0 bottom-0 z-30 mx-auto grid max-w-3xl grid-cols-3 border-t bg-white px-3 pb-[max(12px,env(safe-area-inset-bottom))] pt-2 shadow-2xl">{([{id:'today',label:'Hoje',Icon:Flame},{id:'community',label:'Comunidades',Icon:Users},{id:'discover',label:'Descobrir',Icon:Compass}] as const).map(({id,label,Icon})=><button key={id} onClick={()=>setTab(id)} className={`flex min-h-14 flex-col items-center justify-center rounded-2xl text-xs font-black ${tab===id?'bg-blue-100 text-blue-700':'text-slate-500'}`}><Icon className="h-5 w-5"/>{label}</button>)}</nav></div>}
